### ISSUE TITLE
Proposing a new variation axis to OpenType

### ISSUE THREAD

**Issue by ebraminio** [simoncozens/lottie2vf#4]
https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg#how-to-register-a-design-variation-axis-tag

suggests proposing new axis to OpenType so I was thinking what if we can reach to a consensus and go for a new registered axis.

I'm thinking about a new axis, called `time` maybe, like the naming in https://github.com/Typogram/Anicons but using seconds as the value can be a good start. `fvar`'s max value can be a good indication of how animations on the specific font take long. This proposal assumes all the glyphs in a specific font will have a fixed time length. For example all the stickers in Telegram have 3 seconds fixed length https://core.telegram.org/stickers#animation-requirements and in here we just have font wide fixed time length which can be changed from font to font.

Another idea can be considering a global fixed length, say from 0 to 1, for all of the fonts, and then maybe having a table called `time` that indicates how long every specific animation should take in real world time. That way there won't be font specific time length and every glyph can be configured separately. And then that choosing a specific range for `time` axis value can be even unnecessary as that `time` table can specify what is the relation between the variation axis and real world time. And maybe that `time` table can be done inside `GDEF` or something.

Not sure if here is the best place to propose this, I thought I can at least propose that to one of the most promising implementations of this and I thought you can help me on how we can proceed this that will finally help this work also I think. Thanks!

**Comment by simoncozens** [comment]
In reality, proposing axes to Microsoft never seems to go anywhere - there have been zero registered axes added to OT since variations happened. You're probably better trying the Google Fonts [axis registry](https://github.com/googlefonts/axisregistry) if you have a particular font you want to onboard. I don't, so I'm not going to take this forward, but will support the creation of a time/animation axis if you decide to do so!

**Comment by ebraminio** [comment]
Understandable. Thanks

**Comment by ebraminio** [comment]
Understandable, filed as https://github.com/googlefonts/axisregistry/issues/152. Thanks

**Comment by davelab6** [comment]
Thanks @ebraminio
